/*
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.ui.tests;

import com.google.inject.Injector;
import kcl.mmdd.course.languages.lobster.ui.internal.LobsterActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LobsterLanguagesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LobsterActivator.getInstance().getInjector("kcl.mmdd.course.languages.lobster.LobsterLanguages");
	}

}
