/**
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.lobsterLanguages;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Char Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.CharLiteral#getVac <em>Vac</em>}</li>
 * </ul>
 *
 * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getCharLiteral()
 * @model
 * @generated
 */
public interface CharLiteral extends PrimaryExpression
{
  /**
   * Returns the value of the '<em><b>Vac</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vac</em>' attribute.
   * @see #setVac(String)
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getCharLiteral_Vac()
   * @model
   * @generated
   */
  String getVac();

  /**
   * Sets the value of the '{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.CharLiteral#getVac <em>Vac</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vac</em>' attribute.
   * @see #getVac()
   * @generated
   */
  void setVac(String value);

} // CharLiteral
