/**
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.lobsterLanguages;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Table Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.CreateTableStatement#getTbname <em>Tbname</em>}</li>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.CreateTableStatement#getDbname <em>Dbname</em>}</li>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.CreateTableStatement#getColumns <em>Columns</em>}</li>
 * </ul>
 *
 * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getCreateTableStatement()
 * @model
 * @generated
 */
public interface CreateTableStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Tbname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tbname</em>' containment reference.
   * @see #setTbname(PrimaryExpression)
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getCreateTableStatement_Tbname()
   * @model containment="true"
   * @generated
   */
  PrimaryExpression getTbname();

  /**
   * Sets the value of the '{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.CreateTableStatement#getTbname <em>Tbname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tbname</em>' containment reference.
   * @see #getTbname()
   * @generated
   */
  void setTbname(PrimaryExpression value);

  /**
   * Returns the value of the '<em><b>Dbname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dbname</em>' containment reference.
   * @see #setDbname(PrimaryExpression)
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getCreateTableStatement_Dbname()
   * @model containment="true"
   * @generated
   */
  PrimaryExpression getDbname();

  /**
   * Sets the value of the '{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.CreateTableStatement#getDbname <em>Dbname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dbname</em>' containment reference.
   * @see #getDbname()
   * @generated
   */
  void setDbname(PrimaryExpression value);

  /**
   * Returns the value of the '<em><b>Columns</b></em>' containment reference list.
   * The list contents are of type {@link kcl.mmdd.course.languages.lobster.lobsterLanguages.CreateTableColumn}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' containment reference list.
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getCreateTableStatement_Columns()
   * @model containment="true"
   * @generated
   */
  EList<CreateTableColumn> getColumns();

} // CreateTableStatement
