/**
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.lobsterLanguages;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Database Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.CreateDatabaseStatement#getDbname <em>Dbname</em>}</li>
 * </ul>
 *
 * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getCreateDatabaseStatement()
 * @model
 * @generated
 */
public interface CreateDatabaseStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Dbname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dbname</em>' containment reference.
   * @see #setDbname(PrimaryExpression)
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getCreateDatabaseStatement_Dbname()
   * @model containment="true"
   * @generated
   */
  PrimaryExpression getDbname();

  /**
   * Sets the value of the '{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.CreateDatabaseStatement#getDbname <em>Dbname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dbname</em>' containment reference.
   * @see #getDbname()
   * @generated
   */
  void setDbname(PrimaryExpression value);

} // CreateDatabaseStatement
