/**
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.lobsterLanguages;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete Data Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.DeleteDataStatement#getCondition <em>Condition</em>}</li>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.DeleteDataStatement#getTbname <em>Tbname</em>}</li>
 * </ul>
 *
 * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getDeleteDataStatement()
 * @model
 * @generated
 */
public interface DeleteDataStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference list.
   * The list contents are of type {@link kcl.mmdd.course.languages.lobster.lobsterLanguages.MoreConditionStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference list.
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getDeleteDataStatement_Condition()
   * @model containment="true"
   * @generated
   */
  EList<MoreConditionStatement> getCondition();

  /**
   * Returns the value of the '<em><b>Tbname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tbname</em>' containment reference.
   * @see #setTbname(PrimaryExpression)
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getDeleteDataStatement_Tbname()
   * @model containment="true"
   * @generated
   */
  PrimaryExpression getTbname();

  /**
   * Sets the value of the '{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.DeleteDataStatement#getTbname <em>Tbname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tbname</em>' containment reference.
   * @see #getTbname()
   * @generated
   */
  void setTbname(PrimaryExpression value);

} // DeleteDataStatement
