/**
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.lobsterLanguages;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete Table Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.DeleteTableStatement#getTbname <em>Tbname</em>}</li>
 * </ul>
 *
 * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getDeleteTableStatement()
 * @model
 * @generated
 */
public interface DeleteTableStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Tbname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tbname</em>' containment reference.
   * @see #setTbname(PrimaryExpression)
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getDeleteTableStatement_Tbname()
   * @model containment="true"
   * @generated
   */
  PrimaryExpression getTbname();

  /**
   * Sets the value of the '{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.DeleteTableStatement#getTbname <em>Tbname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tbname</em>' containment reference.
   * @see #getTbname()
   * @generated
   */
  void setTbname(PrimaryExpression value);

} // DeleteTableStatement
