/**
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.lobsterLanguages;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.InsertStatement#getColumn <em>Column</em>}</li>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.InsertStatement#getValue <em>Value</em>}</li>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.InsertStatement#getTbname <em>Tbname</em>}</li>
 * </ul>
 *
 * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getInsertStatement()
 * @model
 * @generated
 */
public interface InsertStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Column</b></em>' containment reference list.
   * The list contents are of type {@link kcl.mmdd.course.languages.lobster.lobsterLanguages.PrimaryExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' containment reference list.
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getInsertStatement_Column()
   * @model containment="true"
   * @generated
   */
  EList<PrimaryExpression> getColumn();

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference list.
   * The list contents are of type {@link kcl.mmdd.course.languages.lobster.lobsterLanguages.PrimaryExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference list.
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getInsertStatement_Value()
   * @model containment="true"
   * @generated
   */
  EList<PrimaryExpression> getValue();

  /**
   * Returns the value of the '<em><b>Tbname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tbname</em>' containment reference.
   * @see #setTbname(PrimaryExpression)
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getInsertStatement_Tbname()
   * @model containment="true"
   * @generated
   */
  PrimaryExpression getTbname();

  /**
   * Sets the value of the '{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.InsertStatement#getTbname <em>Tbname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tbname</em>' containment reference.
   * @see #getTbname()
   * @generated
   */
  void setTbname(PrimaryExpression value);

} // InsertStatement
