/**
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.lobsterLanguages;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>More Condition Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.MoreConditionStatement#getColumn <em>Column</em>}</li>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.MoreConditionStatement#getValue <em>Value</em>}</li>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.MoreConditionStatement#getMorecondition <em>Morecondition</em>}</li>
 * </ul>
 *
 * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getMoreConditionStatement()
 * @model
 * @generated
 */
public interface MoreConditionStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Column</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' containment reference.
   * @see #setColumn(PrimaryExpression)
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getMoreConditionStatement_Column()
   * @model containment="true"
   * @generated
   */
  PrimaryExpression getColumn();

  /**
   * Sets the value of the '{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.MoreConditionStatement#getColumn <em>Column</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column</em>' containment reference.
   * @see #getColumn()
   * @generated
   */
  void setColumn(PrimaryExpression value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(PrimaryExpression)
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getMoreConditionStatement_Value()
   * @model containment="true"
   * @generated
   */
  PrimaryExpression getValue();

  /**
   * Sets the value of the '{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.MoreConditionStatement#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(PrimaryExpression value);

  /**
   * Returns the value of the '<em><b>Morecondition</b></em>' attribute.
   * The literals are from the enumeration {@link kcl.mmdd.course.languages.lobster.lobsterLanguages.MoreCondition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Morecondition</em>' attribute.
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.MoreCondition
   * @see #setMorecondition(MoreCondition)
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage#getMoreConditionStatement_Morecondition()
   * @model
   * @generated
   */
  MoreCondition getMorecondition();

  /**
   * Sets the value of the '{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.MoreConditionStatement#getMorecondition <em>Morecondition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Morecondition</em>' attribute.
   * @see kcl.mmdd.course.languages.lobster.lobsterLanguages.MoreCondition
   * @see #getMorecondition()
   * @generated
   */
  void setMorecondition(MoreCondition value);

} // MoreConditionStatement
