/**
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.lobsterLanguages.impl;

import java.util.Collection;

import kcl.mmdd.course.languages.lobster.lobsterLanguages.InsertStatement;
import kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage;
import kcl.mmdd.course.languages.lobster.lobsterLanguages.PrimaryExpression;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Insert Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.impl.InsertStatementImpl#getColumn <em>Column</em>}</li>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.impl.InsertStatementImpl#getValue <em>Value</em>}</li>
 *   <li>{@link kcl.mmdd.course.languages.lobster.lobsterLanguages.impl.InsertStatementImpl#getTbname <em>Tbname</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InsertStatementImpl extends StatementImpl implements InsertStatement
{
  /**
   * The cached value of the '{@link #getColumn() <em>Column</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumn()
   * @generated
   * @ordered
   */
  protected EList<PrimaryExpression> column;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected EList<PrimaryExpression> value;

  /**
   * The cached value of the '{@link #getTbname() <em>Tbname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTbname()
   * @generated
   * @ordered
   */
  protected PrimaryExpression tbname;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InsertStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LobsterLanguagesPackage.Literals.INSERT_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PrimaryExpression> getColumn()
  {
    if (column == null)
    {
      column = new EObjectContainmentEList<PrimaryExpression>(PrimaryExpression.class, this, LobsterLanguagesPackage.INSERT_STATEMENT__COLUMN);
    }
    return column;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PrimaryExpression> getValue()
  {
    if (value == null)
    {
      value = new EObjectContainmentEList<PrimaryExpression>(PrimaryExpression.class, this, LobsterLanguagesPackage.INSERT_STATEMENT__VALUE);
    }
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrimaryExpression getTbname()
  {
    return tbname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTbname(PrimaryExpression newTbname, NotificationChain msgs)
  {
    PrimaryExpression oldTbname = tbname;
    tbname = newTbname;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LobsterLanguagesPackage.INSERT_STATEMENT__TBNAME, oldTbname, newTbname);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTbname(PrimaryExpression newTbname)
  {
    if (newTbname != tbname)
    {
      NotificationChain msgs = null;
      if (tbname != null)
        msgs = ((InternalEObject)tbname).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LobsterLanguagesPackage.INSERT_STATEMENT__TBNAME, null, msgs);
      if (newTbname != null)
        msgs = ((InternalEObject)newTbname).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LobsterLanguagesPackage.INSERT_STATEMENT__TBNAME, null, msgs);
      msgs = basicSetTbname(newTbname, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LobsterLanguagesPackage.INSERT_STATEMENT__TBNAME, newTbname, newTbname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LobsterLanguagesPackage.INSERT_STATEMENT__COLUMN:
        return ((InternalEList<?>)getColumn()).basicRemove(otherEnd, msgs);
      case LobsterLanguagesPackage.INSERT_STATEMENT__VALUE:
        return ((InternalEList<?>)getValue()).basicRemove(otherEnd, msgs);
      case LobsterLanguagesPackage.INSERT_STATEMENT__TBNAME:
        return basicSetTbname(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LobsterLanguagesPackage.INSERT_STATEMENT__COLUMN:
        return getColumn();
      case LobsterLanguagesPackage.INSERT_STATEMENT__VALUE:
        return getValue();
      case LobsterLanguagesPackage.INSERT_STATEMENT__TBNAME:
        return getTbname();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LobsterLanguagesPackage.INSERT_STATEMENT__COLUMN:
        getColumn().clear();
        getColumn().addAll((Collection<? extends PrimaryExpression>)newValue);
        return;
      case LobsterLanguagesPackage.INSERT_STATEMENT__VALUE:
        getValue().clear();
        getValue().addAll((Collection<? extends PrimaryExpression>)newValue);
        return;
      case LobsterLanguagesPackage.INSERT_STATEMENT__TBNAME:
        setTbname((PrimaryExpression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LobsterLanguagesPackage.INSERT_STATEMENT__COLUMN:
        getColumn().clear();
        return;
      case LobsterLanguagesPackage.INSERT_STATEMENT__VALUE:
        getValue().clear();
        return;
      case LobsterLanguagesPackage.INSERT_STATEMENT__TBNAME:
        setTbname((PrimaryExpression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LobsterLanguagesPackage.INSERT_STATEMENT__COLUMN:
        return column != null && !column.isEmpty();
      case LobsterLanguagesPackage.INSERT_STATEMENT__VALUE:
        return value != null && !value.isEmpty();
      case LobsterLanguagesPackage.INSERT_STATEMENT__TBNAME:
        return tbname != null;
    }
    return super.eIsSet(featureID);
  }

} //InsertStatementImpl
