/*
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.ide;


/**
 * Use this class to register ide components.
 */
public class LobsterLanguagesIdeModule extends AbstractLobsterLanguagesIdeModule {
}
