/*
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import kcl.mmdd.course.languages.lobster.LobsterLanguagesRuntimeModule;
import kcl.mmdd.course.languages.lobster.LobsterLanguagesStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LobsterLanguagesIdeSetup extends LobsterLanguagesStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LobsterLanguagesRuntimeModule(), new LobsterLanguagesIdeModule()));
	}
	
}
