/*
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class LobsterLanguagesProposalProvider extends AbstractLobsterLanguagesProposalProvider {
}
