/*
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.ui;

import com.google.inject.Injector;
import kcl.mmdd.course.languages.lobster.ui.internal.LobsterActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LobsterLanguagesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LobsterActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LobsterActivator activator = LobsterActivator.getInstance();
		return activator != null ? activator.getInjector(LobsterActivator.KCL_MMDD_COURSE_LANGUAGES_LOBSTER_LOBSTERLANGUAGES) : null;
	}

}
