/*
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LobsterLanguagesStandaloneSetup extends LobsterLanguagesStandaloneSetupGenerated {

	public static void doSetup() {
		new LobsterLanguagesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
