/*
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLobsterLanguagesValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(kcl.mmdd.course.languages.lobster.lobsterLanguages.LobsterLanguagesPackage.eINSTANCE);
		return result;
	}
}
