/*
 * generated by Xtext 2.24.0
 */
package kcl.mmdd.course.languages.lobster.parser.antlr;

import com.google.inject.Inject;
import kcl.mmdd.course.languages.lobster.parser.antlr.internal.InternalLobsterLanguagesParser;
import kcl.mmdd.course.languages.lobster.services.LobsterLanguagesGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LobsterLanguagesParser extends AbstractAntlrParser {

	@Inject
	private LobsterLanguagesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLobsterLanguagesParser createParser(XtextTokenStream stream) {
		return new InternalLobsterLanguagesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LobsterProgram";
	}

	public LobsterLanguagesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LobsterLanguagesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
